# Theme settings
doks:
    url: 'https://lemulli.github.io/'
    baseurl: ''
    color_theme: yellow # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Lee Mullins
            image:
        nav:
            - item_name: Projects
              item_url: '/home'
            - item_name: About
              item_url: '/about'

    # Author settings
    author:
        name: Lee Mullins
        image: /doks-theme/assets/images/author/author.jpg
        bio: Your bio description here
        social:
            github: lemulli
            email: lee.ellen.mullins@gmail.com
    footer:
        content:
            logo:
                text: 
                image:
            copyright: Copyright &copy; 2024. - Lee Mullins <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/lemulli'
            - network_name: linkedin
              profile_url: 'https://linkedin.com/in/lemulli'
            - network_name: youtube
              profile_url: 'https://youtube.com/@lemulli'

    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
